// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkqNiuByuEk9St6QWA9OIMsRx19Q7OWeY',
    appId: '1:635956052976:web:038d36de5ab35ec8f11335',
    messagingSenderId: '635956052976',
    projectId: 'sitequant-8842d',
    authDomain: 'sitequant-8842d.firebaseapp.com',
    storageBucket: 'sitequant-8842d.firebasestorage.app',
    measurementId: 'G-W0VMX4PJJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAjWmh2bK-kY9Ww4YX8kUd16z3jXAnams',
    appId: '1:635956052976:android:222f7656c33c2719f11335',
    messagingSenderId: '635956052976',
    projectId: 'sitequant-8842d',
    storageBucket: 'sitequant-8842d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwu1RVn10Zxq0ZkEZAS3nOmcBH1-myfZ8',
    appId: '1:635956052976:ios:9d4faadbbf7952aef11335',
    messagingSenderId: '635956052976',
    projectId: 'sitequant-8842d',
    storageBucket: 'sitequant-8842d.firebasestorage.app',
    iosBundleId: 'com.sitequant.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwu1RVn10Zxq0ZkEZAS3nOmcBH1-myfZ8',
    appId: '1:635956052976:ios:40bf2095152b18c4f11335',
    messagingSenderId: '635956052976',
    projectId: 'sitequant-8842d',
    storageBucket: 'sitequant-8842d.firebasestorage.app',
    iosBundleId: 'com.example.siteQuant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkqNiuByuEk9St6QWA9OIMsRx19Q7OWeY',
    appId: '1:635956052976:web:e5c8e46f1c602acaf11335',
    messagingSenderId: '635956052976',
    projectId: 'sitequant-8842d',
    authDomain: 'sitequant-8842d.firebaseapp.com',
    storageBucket: 'sitequant-8842d.firebasestorage.app',
    measurementId: 'G-DDX8R6V3VN',
  );
}
